"""Add task notification flags

Revision ID: c6b68b6084d2
Revises: 
Create Date: 2025-11-30 17:05:36.635066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b68b6084d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_today_notified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('overdue_notified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('overdue_notified')
        batch_op.drop_column('due_today_notified')

    # ### end Alembic commands ###
